public enum TokenType {
	// NOTE: Code will only work of UNDEFINED is the LAST value in the enumeration!
	INTEGER, VARIABLE, FUNCTION, PLUS, MINUS, TIMES, LESSTHAN, GREATERTHAN, EQEQ, EQ, LBRACE, RBRACE, LPAREN, RPAREN, COMMA, FUNCTIONSTART, SEMICOLON, IF
}